train_data: dataset/train.jsonl
train_tables: dataset/train.tables.jsonl
dev_data: dataset/dev.jsonl
dev_tables: dataset/dev.tables.jsonl
test_data: dataset/test.jsonl
test_tables: dataset/test.tables.jsonl
preprocessed_data_path: dataset/all_data.pickle
tf_hub_model: https://tfhub.dev/google/Wiki-words-500/2
batch_size: 128
real_proxy_token: <real>
pad_token: <pad>
num_epochs: 10
train_index: ann_index/train_ann_index.ann
include_hardest_negatives: True
include_random_negatives: True
model_dir: saved_models
model_name: test
contrastive_loss_margin: 0.5
learning_rate: 0.0001
execute_greedily: False
index_dir: ann_index
train_tables_index: train_tables.ann
dev_tables_index: dev_tables.ann
test_tables_index: test_tables.ann
dim: 500